added order applications by category in start menu
wnayes/bond-wm pull request #15
Opened 2024-09-04 19:44 UTC by danielmeloalencar

I understand that you plan to keep the core functionality in bond-wm and the other features should be added as separate packages. But I believe this contribution is still essential, I don't know if exactly in this way, but it should be something to consider.

This contribution organizes the applications into categories for better viewing.
![image](https://github.com/user-attachments/assets/cbf67fe3-43f0-498e-8153-e45f9ad6ca7a)

2024-09-04 23:02 UTC, wnayes commented
Yeah this sort of change looks like it will be nice to have. The start menu is very much bare bones and could use improvements like these. I will take a closer look later.

2024-09-06 03:17 UTC, danielmeloalencar commented
Do you want me to correct something so you can accept the PR? Or do you not accept contributions?

2024-09-06 13:30 UTC, wnayes commented
Can you run `pnpm prettier` before we merge this to update with matching formatting?

The following are not necessary to merge this, but some ideas in case you want to add them:

- There is a [standard set of categories](https://specifications.freedesktop.org/menu-spec/latest/category-registry.html) that we can expect. It would be nice if we had a map to map from identifier to display name, like `"AudioVideo" -> "Audio / Video"` and `"PackageManager" -> "Package Manager"`.
- Eventually, I might like this behavior to be controlled by a prop, e.g. `<StartMenuApplicationList groupBy="categories"  />`

2024-09-06 13:30 UTC, wnayes requested changes

2024-09-06 13:30 UTC, wnayes commented on apps/wm/desktopEntries.ts
> +      if (category !== 'Others' && existingCategories.has(category)) {
It seems like `existingCategories` will be empty for the first entry, which could mean some entry gets assigned to Others incorrectly. The `existingCategories` set is potentially not needed if we instead say that `assignedCategory = categories[0]`.

2024-09-06 13:30 UTC, wnayes commented on apps/wm/desktopEntries.ts
> +    const categories = typeof categoriesValue === 'object' ? categoriesValue : ['Others'];
Would prefer `Array.isArray(categoriesValue) ? categoriesValue : ["Others"]`

2024-09-06 17:48 UTC, danielmeloalencar commented
> Can you run `pnpm prettier` before we merge this to update with matching formatting?
> 
> The following are not necessary to merge this, but some ideas in case you want to add them:
> 
> * There is a [standard set of categories](https://specifications.freedesktop.org/menu-spec/latest/category-registry.html) that we can expect. It would be nice if we had a map to map from identifier to display name, like `"AudioVideo" -> "Audio / Video"` and `"PackageManager" -> "Package Manager"`.
> * Eventually, I might like this behavior to be controlled by a prop, e.g. `<StartMenuApplicationList groupBy="categories"  />`

Thanks for the feedback! I've already run pnpm prettier and made the recommended corrections. Everything should be in order now. I appreciate the additional suggestions and will keep them in mind for future improvements!

2024-09-07 19:07 UTC, danielmeloalencar commented
Is everything ok?

2024-09-07 19:11 UTC, wnayes commented
I am away from my computer this weekend, I will try to look by Sunday
night. Thanks for making the changes.

On Sat, Sep 7, 2024, 2:07 PM Daniel Melo Alencar ***@***.***>
wrote:

> Is everything ok?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wnayes/bond-wm/pull/15#issuecomment-2336408743>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAK2FCSMBJ43NAOA56O7AG3ZVNFHFAVCNFSM6AAAAABNVAKAFOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZWGQYDQNZUGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-09-08 22:52 UTC, merged