Da startmenu group by
wnayes/bond-wm pull request #17
Opened 2024-09-10 17:30 UTC by danielmeloalencar

### Description of Changes

**Feature: Group Applications by Categories or All**
![image](https://github.com/user-attachments/assets/c671bd7d-b3a2-4cfb-a6ca-1c35eaa20ae3)

This pull request adds the option to group applications in the start menu by categories or display them all in a single list. The default view is by categories, and the user can toggle between views using a button.

### Changes:

- **`groupBy` Property:** Added to `StartMenuApplicationList`, with options `"categories"` (default) and `"all"`.
- **`toggleGroupBy` Function:** Implemented to switch between grouping modes.
- **`categorizedEntries` Memo:** Organizes entries based on the selected grouping option.
- **Styles (CSS):** Added a toggle button in the application list header.

### Future Considerations:
- **Preference Persistence:** Add persistence for the grouping preference across sessions.
- **UI Enhancement:** Replace the "Category" and "All" texts with icons for a more intuitive interface.

2024-09-12 03:19 UTC, wnayes requested changes
Thanks for submitting this!

I think my comments are mostly minor.

Since you mention a persistence feature, I want to mention how I would approach / think about something like that. Since this window manager is aimed towards web developers, and requires establishing a local config directory, my general expectation is that users of the window manager will tweak their config to their liking. So I don't see a need for a persistence feature, because if someone wants a particular default, they'll set it in JSX in their config. The config is effectively the persistence mechanism for configuring defaults.

For this groupBy feature, I think it is reasonable to be able to toggle the grouping dynamically at runtime. But I'd probably draw the line at persisting what can instead be defined statically to the user's preference.

2024-09-12 03:19 UTC, wnayes commented on packages/react-start-menu/StartMenuApplicationList.tsx
> +import "./StartMenuStyles.css";
I am curious what this CSS import does, since in order for CSS to load into a ChildWindow, the StartMenu.tsx uses a `<Stylesheet />` component. (The component makes use of context to know what window to load the CSS into.)

2024-09-12 03:19 UTC, wnayes commented on packages/react-start-menu/StartMenuApplicationList.tsx
> +      <div className="listHeader">
These class names are a little too general I think, given that we don't (currently) use any sort of scoping mechanism like CSS modules to isolate between files. Would prefer if they start with `startMenu`.

2024-09-12 03:19 UTC, wnayes commented on packages/react-start-menu/StartMenuApplicationList.tsx
> +      <div className="listHeader">
I'd like to see a prop like `showGroupByToggle` that controls whether this part of the DOM is rendered at all.

2024-09-12 03:46 UTC, danielmeloalencar commented on packages/react-start-menu/StartMenuApplicationList.tsx
> +import "./StartMenuStyles.css";
You're right. Sorry.

2024-09-12 03:48 UTC, danielmeloalencar commented
I made the requested adjustments

2024-09-14 00:38 UTC, wnayes approved these changes

2024-09-14 00:38 UTC, merged